# Generated by Django 3.2.6 on 2021-11-09 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tb_track_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traineeenroll',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tb_track_app.programminglanguage'),
        ),
        migrations.DeleteModel(
            name='TraineeFees',
        ),
    ]
