# Generated by Django 3.2.6 on 2021-11-09 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tb_track_app', '0002_auto_20211109_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traineeenroll',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tb_track_app.programminglanguage'),
        ),
        migrations.CreateModel(
            name='TraineeFees',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fees_paid', models.PositiveIntegerField(null=True)),
                ('balance_fee', models.PositiveIntegerField(null=True)),
                ('date', models.DateField()),
                ('remarks', models.TextField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tb_track_app.batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tb_track_app.course')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tb_track_app.programminglanguage')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tb_track_app.trainee')),
            ],
            options={
                'db_table': '"trainee_fees"',
            },
        ),
    ]
