# Generated by Django 3.2.6 on 2021-11-10 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tb_track_app', '0003_auto_20211109_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traineefees',
            old_name='fees_paid',
            new_name='amount_paid',
        ),
        migrations.AddField(
            model_name='traineefees',
            name='total_fees_paid',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='TraineerFees',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('salary_paid', models.PositiveIntegerField(null=True)),
                ('balance_salary', models.PositiveIntegerField(null=True)),
                ('date', models.DateField()),
                ('remarks', models.TextField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tb_track_app.batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tb_track_app.course')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tb_track_app.programminglanguage')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tb_track_app.trainee')),
            ],
            options={
                'db_table': '"trainer_fees"',
            },
        ),
        migrations.CreateModel(
            name='CourseFees',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course_fee', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tb_track_app.course')),
            ],
            options={
                'db_table': '"course_fees"',
            },
        ),
    ]
