# Generated by Django 3.2.6 on 2021-11-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tb_track_app', '0004_auto_20211110_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='traineefees',
            name='contact',
            field=models.CharField(default=True, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traineerfees',
            name='contact',
            field=models.CharField(default=True, max_length=12),
            preserve_default=False,
        ),
    ]
