# Generated by Django 3.2.6 on 2021-11-11 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tb_track_app', '0005_auto_20211110_1542'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TraineerFees',
            new_name='TrainerFees',
        ),
    ]
