# Generated by Django 3.2.6 on 2021-11-15 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tb_track_app', '0010_auto_20211113_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerPayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contact', models.CharField(max_length=12)),
                ('amount_paid', models.PositiveIntegerField(null=True)),
                ('balance_salary', models.PositiveIntegerField(null=True)),
                ('total_amount_paid', models.PositiveIntegerField(null=True)),
                ('date', models.DateField()),
                ('remarks', models.TextField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tb_track_app.batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tb_track_app.course')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tb_track_app.programminglanguage')),
            ],
            options={
                'db_table': '"trainer_payment"',
            },
        ),
        migrations.AddField(
            model_name='trainer',
            name='fixed_monthly_salary',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='trainer',
            name='salary_percent',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='trainer',
            name='variable_salary_percent',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.DeleteModel(
            name='TrainerFees',
        ),
        migrations.AddField(
            model_name='trainerpayment',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tb_track_app.trainer'),
        ),
    ]
