# Generated by Django 3.2.6 on 2021-11-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tb_track_app', '0013_trainerpayment_amount_to_be_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
