# Generated by Django 3.2.6 on 2021-11-16 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tb_track_app', '0014_batch_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='language',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='BatchFees',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_fee_batch', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tb_track_app.batch')),
                ('course_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tb_track_app.coursefees')),
            ],
            options={
                'db_table': '"batch_fees"',
            },
        ),
    ]
