# Generated by Django 3.2.8 on 2021-12-31 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tb_track_app', '0018_auto_20211231_0852'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='communityform',
            table='"community_form"',
        ),
    ]
