# Generated by Django 3.2.8 on 2021-12-31 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tb_track_app', '0019_alter_communityform_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityform',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='communityform',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='communityform',
            name='hearus',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='communityform',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='communityform',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='communityform',
            name='technology',
            field=models.CharField(max_length=100),
        ),
    ]
