# Generated by Django 3.2.8 on 2022-01-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tb_track_app', '0021_auto_20211231_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityform',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
