# Generated by Django 4.0.3 on 2022-03-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commitInfo', '0002_rename_fname_commitinfo_author_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitinfo',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
