# Generated by Django 4.0.3 on 2022-03-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commitInfo', '0003_alter_commitinfo_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commitinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='commitinfo',
            name='commit_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
