# Generated by Django 4.0.3 on 2022-03-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='servers',
            fields=[
                ('instance_name', models.CharField(max_length=255)),
                ('instance_id', models.AutoField(primary_key=True, serialize=False)),
                ('instance_type', models.CharField(max_length=255)),
                ('private_ip', models.CharField(max_length=255)),
                ('public_ip', models.CharField(max_length=255)),
                ('instance_role', models.CharField(max_length=255)),
                ('environment', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('security_group', models.CharField(max_length=255)),
                ('avail_zone', models.CharField(max_length=255)),
                ('subnet_id', models.CharField(max_length=255)),
                ('vpc_id', models.CharField(max_length=255)),
                ('arch_type', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'server_inventory',
            },
        ),
    ]
