# Generated by Django 4.0.3 on 2022-03-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awsinventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='db',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('db_name', models.CharField(max_length=255)),
                ('db_instance_name', models.CharField(max_length=255)),
                ('db_type', models.CharField(max_length=255)),
                ('db_storage', models.CharField(max_length=255)),
                ('db_engine', models.CharField(max_length=255)),
                ('db_engine_ver', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('environment', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('workload_type', models.CharField(max_length=255)),
                ('db_endpoint', models.CharField(max_length=255)),
                ('db_vpc_id', models.CharField(max_length=255)),
                ('db_read_replica_db', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'rds_inventory',
            },
        ),
    ]
