# Generated by Django 4.0.3 on 2022-03-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commitInfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commitinfo',
            old_name='fname',
            new_name='author_name',
        ),
        migrations.RenameField(
            model_name='commitinfo',
            old_name='lname',
            new_name='commitmsg',
        ),
        migrations.RenameField(
            model_name='commitinfo',
            old_name='roll',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='commitinfo',
            old_name='sclass',
            new_name='username',
        ),
        migrations.AddField(
            model_name='commitinfo',
            name='commit_id',
            field=models.TextField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commitinfo',
            name='created_on',
            field=models.TimeField(default=True),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='commitinfo',
            table='commit_information',
        ),
    ]
